# Generated by Django 4.0.3 on 2022-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sign_address_sign_dob_sign_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='dob',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
