# Generated by Django 4.0.3 on 2022-07-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_sign_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='uname',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
