# Generated by Django 4.0.3 on 2022-07-29 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_itemcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
