# Generated by Django 4.0.3 on 2022-07-31 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_adminsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocname', models.CharField(max_length=100)),
                ('ocurl', models.CharField(max_length=500)),
                ('ocprice', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('uname', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
